# See https:#eslint.org/docs/user-guide/configuring
root: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
env:
  browser: true
  es2022: true
  jest: true
# Check JS inside HTML files
plugins: [html]
extends:
  # Use eslint recommended rules by default
  - eslint:recommended
  # docs/network-react uses React
  - plugin:react/recommended
  - plugin:react-hooks/recommended
rules:
  # From React 17+, we don't need to import React
  react/react-in-jsx-scope: 'off'
